# Generated by Django 4.2.4 on 2023-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='datetime_string',
            field=models.CharField(default='YYYY-MM-DD HH:MM:SS', max_length=19),
        ),
    ]
